import { readFileSync } from 'node:fs'
import { describe, expect, it } from 'vitest'

// 契约漂移守卫。
//
// `docs/openapi.yaml` 是 HTTP 契约的唯一出处，`src/api/schema.d.ts` 是它生成出来的影子。
// 二者之间没有编译期联系：改了契约却忘了 `npm run gen:api`，前端会拿着过期类型继续编译通过，
// 直到联调时才发现字段/路径对不上。这条测试把“忘了重新生成”变成一条会红的断言。
//
// 这里刻意用文本比对而不是解析 YAML：解析需要引入 YAML 依赖，而这里要证明的事情只有一件——
// “生成物里确实有契约里那些路径与错误码”。文本包含足以证明它。
const frontendRoot = new URL('../../', import.meta.url)
const repoRoot = new URL('../../../', import.meta.url)
// 契约文件在 Windows 工作区里是 CRLF（.gitattributes 只保证入库时是 LF），
// 而生成物永远是 LF。若不归一化，比对会因为换行符而假失败——测试不该关心换行符。
const readText = (url: URL) => readFileSync(url, 'utf8').replace(/\r\n/g, '\n')
const contract = readText(new URL('docs/openapi.yaml', repoRoot))
const generated = readText(new URL('src/api/schema.d.ts', frontendRoot))

/** 契约里 paths 段下声明的所有路径（缩进恰好两格的那一层 key）。 */
function contractPaths(yaml: string): string[] {
  const start = yaml.indexOf('\npaths:\n')
  const end = yaml.indexOf('\ncomponents:')
  expect(start, 'openapi.yaml 里找不到 paths 段').toBeGreaterThan(-1)
  expect(end, 'openapi.yaml 里找不到 components 段').toBeGreaterThan(start)
  const block = yaml.slice(start, end)
  return [...block.matchAll(/^ {2}(\/[^\s:]*):$/gm)].map((m) => m[1]!)
}

/** 契约里 ApiCode 枚举的成员（错误码是全项目共用的词汇表，最不该漂移）。 */
function apiCodeMembers(yaml: string): string[] {
  const start = yaml.indexOf('\n    ApiCode:')
  expect(start, 'openapi.yaml 里找不到 ApiCode schema').toBeGreaterThan(-1)
  const tail = yaml.slice(start).slice(1)
  const nextSchema = tail.search(/\n {4}[A-Za-z]/)
  const block = nextSchema === -1 ? tail : tail.slice(0, nextSchema + 1)
  return [...block.matchAll(/^\s+- ([A-Z_]+)$/gm)].map((m) => m[1]!)
}

describe('openapi.yaml 与生成的类型保持同步', () => {
  it('生成物是自动生成的，不是手写的', () => {
    expect(generated).toContain('auto-generated by openapi-typescript')
  })

  it('契约里的每个路径都出现在生成物里', () => {
    const paths = contractPaths(contract)
    expect(paths.length).toBeGreaterThanOrEqual(18)
    const missing = paths.filter((path) => !generated.includes(`"${path}":`))
    expect(missing, '这些路径改了契约但没重新生成：' + missing.join(', ')).toEqual([])
  })

  it('契约里的每个错误码都出现在生成物里', () => {
    const codes = apiCodeMembers(contract)
    expect(codes).toContain('IDEMPOTENCY_REPLAY')
    const missing = codes.filter((code) => !generated.includes(`"${code}"`))
    expect(missing, '这些错误码改了契约但没重新生成：' + missing.join(', ')).toEqual([])
  })

  it('前后端打交道的关键 schema 都在生成物里', () => {
    for (const schema of [
      'Envelope',
      'LoginRequest',
      'AuthData',
      'User',
      'AuctionSnapshot',
      'BidRequest',
      'BidResult',
      'LedgerEntry',
      'LedgerPage',
      'Wallet',
      'WsTicket',
      'AuctionResult',
      'CreateAuctionRequest',
    ]) {
      expect(generated, `缺少 schema ${schema}`).toContain(`${schema}:`)
    }
  })
})
