/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/ws-tickets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * @description 领一张一次性 WebSocket 入场券（默认 60 秒有效）。
         *
         *     为什么不让客户端把 JWT 直接放进 WS 的 URL：浏览器无法在 WebSocket 握手上自定义头，
         *     令牌只能进查询串，而查询串会落进访问日志与浏览器历史——把一个长效凭证留在日志里。
         *     换成一次性短票后，日志里最坏只会留下一个已作废的字符串。
         *
         *     用法：拿到 ticket 后连 `ws(s)://<host>:<wsPort>/ws/auctions/{auctionId}?ticket=<ticket>`。
         *     票只能核销一次，重复使用会被拒绝（先收到 CONNECTION_STATE(connected=false)，再被断开）。
         */
        post: operations["createWebSocketTicket"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["currentUser"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/wallets/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["currentWallet"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/wallets/me/ledger": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["walletLedger"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auctions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listAuctions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auctions/{auctionId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getAuction"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auctions/{auctionId}/join": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["joinAuction"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auctions/{auctionId}/bids": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listBids"];
        put?: never;
        /**
         * @description 提交出价。幂等键以请求体的 requestId 为准；也可以用 Idempotency-Key 头代替。
         *     重复提交同一个幂等键时返回**首次**结果，code 为 IDEMPOTENCY_REPLAY（HTTP 仍是 200），
         *     客户端据此可以安全重试。
         */
        post: operations["placeBid"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auctions/{auctionId}/result": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["auctionResult"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/auctions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["createAuction"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/auctions/{auctionId}/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["startAuction"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/auctions/{auctionId}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["cancelAuction"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/auctions/{auctionId}/ledger": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description 管理员按场次查看**全部**资金流水，用于确认“最后成交的是 AI 还是人”。
         *     每条流水的 `actorType`（HUMAN/AGENT）标识该笔资金动作的主体。
         *     普通用户无权访问此路由，只能通过 `/wallets/me/ledger` 看到自己的流水。
         */
        get: operations["auctionLedger"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/agent-tokens": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description 管理员总览全部已签发的 Agent Token（**不含明文**），用于审计“现在还有哪些 Agent
         *     能替谁出价”。明文只在签发响应里出现一次，之后无法取回。
         */
        get: operations["listAgentTokens"];
        put?: never;
        post: operations["createAgentToken"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/agent-tokens/{tokenId}/revoke": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * @description 吊销一枚 Agent Token。**幂等**：重复吊销同一枚仍然返回 200（首次吊销的时间戳不变），
         *     因为“让它变成已吊销”是一个可以安全重试的指令；未知 tokenId 才是 404。
         *
         *     响应里的 `token` 恒为 null（吊销后自然拿不回明文），保留该字段只为与签发响应同形。
         */
        post: operations["revokeAgentToken"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/agent-tokens": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description 本人已授权的竞拍 Agent Token 列表（新→旧）。**只返回属于自己的授权，不含明文**：
         *     明文只在签发响应的那一刻出现，之后无法取回。`status` 由服务端按当前时刻判定
         *     （ACTIVE / EXPIRED / REVOKED），客户端不要自行比时间（同 D-27 的口径）。
         */
        get: operations["listMyAgentTokens"];
        put?: never;
        /**
         * @description 为自己签发一枚竞拍 Agent Token（自助授权，见 DECISIONS D-34）。
         *     归属恒为当前登录用户——请求体里没有 `agentUserId`，因此“替别人签发”在契约层面无法表达。
         *     `auctionIds` 省略即“默认拒绍”（D-29）；明文只在本次响应里出现一次。
         */
        post: operations["createMyAgentToken"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/agent-tokens/{tokenId}/revoke": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * @description 吊销自己的 Agent Token。**幂等**（重复吊销仍返回 200）。
         *     不属于本人的 tokenId 返回 404，与“不存在”不可区分，避免拿吊销接口探测他人的 tokenId。
         */
        post: operations["revokeMyAgentToken"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/agent/auctions/{auctionId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description 读取竞拍快照。**这把接口同时也在 8080 上可用**；8090 只是额外的一个最小暴露面，
         *     它上面除了 /agent/** 之外的一切路径都返回 404 封套（连 /health 也没有）。
         *
         *     Agent 凭证的三个失败码分工：401 = 不认识/已过期/已吊销（不区分原因，避免试探）；
         *     403 = 凭证有效但越权（缺权限，或这场拍卖不在 auctionIds 里）；429 = 超出该 Token 的频率上限。
         */
        get: operations["agentAuction"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/agent/auctions/{auctionId}/bids": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["agentBid"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/agent/auctions/{auctionId}/result": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["agentAuctionResult"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Envelope: {
            code: components["schemas"]["ApiCode"];
            /** @example ok */
            message: string;
            data: unknown;
            requestId: string;
        };
        /**
         * @description 业务结果码，所有响应的 code 字段取值。HTTP 状态码与之一一对应：
         *     OK=200；VALIDATION_FAILED=400；UNAUTHENTICATED=401；FORBIDDEN/HUMAN_ONLY_PERIOD=403；
         *     NOT_FOUND=404；METHOD_NOT_ALLOWED=405；其余冲突类=409；RATE_LIMITED=429；INTERNAL_ERROR=500。
         *     客户端应以 code 判定业务结果，不要只依赖 HTTP 状态码。
         *     两个成功码 OK 与 IDEMPOTENCY_REPLAY 都对应 200。
         * @enum {string}
         */
        ApiCode: "OK" | "VALIDATION_FAILED" | "UNAUTHENTICATED" | "FORBIDDEN" | "NOT_FOUND" | "INVALID_STATE" | "BID_TOO_LOW" | "BID_LATE" | "HUMAN_ONLY_PERIOD" | "NOT_JOINED" | "INSUFFICIENT_BALANCE" | "IDEMPOTENCY_REPLAY" | "CONFLICT" | "METHOD_NOT_ALLOWED" | "RATE_LIMITED" | "INTERNAL_ERROR";
        LoginRequest: {
            /** Format: email */
            email: string;
            /** Format: password */
            password: string;
        };
        AuthData: {
            accessToken: string;
            /** Format: date-time */
            expiresAt: string;
            user: components["schemas"]["User"];
        };
        User: {
            id: string;
            name: string;
            /** @enum {string} */
            role: "BIDDER" | "ADMIN";
        };
        /** @enum {string} */
        AuctionStatus: "DRAFT" | "RUNNING" | "SETTLING" | "FINISHED" | "CANCELLED";
        AuctionSnapshot: {
            id: string;
            title: string;
            description?: string;
            status: components["schemas"]["AuctionStatus"];
            startPrice: number;
            minIncrement: number;
            currentPrice: number;
            leader?: string | null;
            /** Format: date-time */
            endsAt?: string | null;
            extensionCount: number;
            participantCount: number;
            seq: number;
            /**
             * @description 尾段“博弈时间”长度（秒）：截止前这段时间内 Agent 一律不得出价，只有真人可以。
             *     由服务端给出而不是让前端硬编码：窗口长度是运营配置（`AUCTION_FINAL_GAME_WINDOW_SECONDS`），
             *     前端只用它做“进入博弈时间”的提示，**不承担任何判定职责**——真正的拒绝对话发生在服务端事务内。
             */
            finalGameWindowSeconds: number;
            /** Format: date-time */
            serverTime: string;
        };
        BidRequest: {
            requestId: string;
            amount: number;
        };
        BidResult: {
            accepted: boolean;
            idempotent: boolean;
            price: number;
            leader?: string | null;
            extensions: number;
            seq: number;
            /** Format: date-time */
            serverTime: string;
        };
        /** @description 一条已接受的出价记录。seq 单调递增，客户端据此检测事件缺口。 */
        Bid: {
            id: string;
            userId: string;
            amount: number;
            requestId: string;
            seq: number;
            /** Format: date-time */
            serverTime: string;
        };
        AuctionPage: {
            items: components["schemas"]["AuctionSnapshot"][];
            page: number;
            size: number;
            total: number;
        };
        BidPage: {
            items: components["schemas"]["Bid"][];
            page: number;
            size: number;
            total: number;
        };
        LedgerPage: {
            items: components["schemas"]["LedgerEntry"][];
            page: number;
            size: number;
            total: number;
        };
        CreateAuctionRequest: {
            title: string;
            description?: string;
            startPrice: number;
            minIncrement: number;
            durationSeconds: number;
        };
        CreateAgentTokenRequest: {
            name: string;
            agentUserId: string;
            auctionIds?: string[];
            scopes: ("auction:read" | "auction:bid")[];
            /** Format: date-time */
            expiresAt: string;
            /** @default 60 */
            rateLimitPerMinute: number;
        };
        CreateMyAgentTokenRequest: {
            name: string;
            auctionIds?: string[];
            scopes: ("auction:read" | "auction:bid")[];
            /** Format: date-time */
            expiresAt: string;
            /** @default 60 */
            rateLimitPerMinute: number;
        };
        AgentTokenSummary: {
            tokenId: string;
            name: string;
            agentUserId: string;
            /**
             * @description 由服务端按当前时刻判定，与鉴权路径的 activeAt 同口径
             * @enum {string}
             */
            status: "ACTIVE" | "EXPIRED" | "REVOKED";
            scopes: ("auction:read" | "auction:bid")[];
            auctionIds: string[];
            rateLimitPerMinute: number;
            /** Format: date-time */
            expiresAt: string;
            /** Format: date-time */
            revokedAt?: string | null;
            /** Format: date-time */
            createdAt: string;
        };
        AgentTokenPage: {
            items: components["schemas"]["AgentTokenSummary"][];
            page: number;
            size: number;
            total: number;
        };
        Wallet: {
            totalBalance: number;
            frozenAmount: number;
            availableBalance: number;
        };
        LedgerEntry: {
            id: string;
            /**
             * @description 该笔资金动作的主体：HUMAN=真人，AGENT=竞拍 Agent。
             *     个人流水只返回本人的记录，因此这个字段不会泄露他人的主体身份。
             * @enum {string}
             */
            actorType: "HUMAN" | "AGENT";
            /** @enum {string} */
            type: "FREEZE" | "RELEASE" | "SETTLE";
            amount: number;
            auctionId?: string | null;
            /**
             * @description 触发本条流水的那次请求的幂等键，用于把资金变动追回到具体出价/结算。
             *     结算产生的流水没有客户端请求，此处可能为空。
             */
            requestId?: string | null;
            /** Format: date-time */
            createdAt: string;
        };
        ErrorData: {
            [key: string]: unknown;
        };
        WsTicket: {
            /** @description 一次性入场券。base64url、无填充，可直接放进查询串。 */
            ticket: string;
            /** Format: date-time */
            expiresAt: string;
            /**
             * @description 连接路径模板，把 `{auctionId}` 换成目标拍品 ID。服务端给出而不是让前端硬编码：
             *     路径属于契约，改一次就该只改一处。
             */
            wsPath: string;
            /**
             * @description WebSocket 监听的端口。它与 HTTP 端口**不同**（默认是 `WS_PORT`，没配时是 HTTP 端口 + 10000），
             *     因此必须由服务端告知，客户端不能拿它当 80/443 去拼。
             */
            wsPort: number;
        };
        Participant: {
            auctionId?: string;
            userId?: string;
            /** Format: date-time */
            joinedAt?: string;
        };
        AuctionResult: {
            auctionId: string;
            status: components["schemas"]["AuctionStatus"];
            winner?: string | null;
            /**
             * @description 成交主体：HUMAN=真人，AGENT=竞拍 Agent；未成交时为 null。
             *     这是隐私字段——仅当请求者是赢家本人或管理员时才有值，其余一律为 null。
             * @enum {string|null}
             */
            winnerType?: "HUMAN" | "AGENT" | null;
            finalPrice: number;
            /** @enum {string} */
            reason: "TIMEOUT" | "NO_BIDS" | "CANCELLED";
            /** Format: date-time */
            settledAt?: string | null;
        };
        AgentToken: {
            token?: string;
            tokenId?: string;
            /** Format: date-time */
            expiresAt?: string;
        };
    };
    responses: {
        /** @description OK */
        EnvelopeAuth: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Envelope"] & {
                    data?: components["schemas"]["AuthData"];
                };
            };
        };
        /** @description OK */
        EnvelopeWsTicket: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Envelope"] & {
                    data?: components["schemas"]["WsTicket"];
                };
            };
        };
        /** @description OK */
        EnvelopeUser: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Envelope"] & {
                    data?: components["schemas"]["User"];
                };
            };
        };
        /** @description OK */
        EnvelopeWallet: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Envelope"] & {
                    data?: components["schemas"]["Wallet"];
                };
            };
        };
        /** @description OK */
        EnvelopeLedgerPage: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Envelope"] & {
                    data?: components["schemas"]["LedgerPage"];
                };
            };
        };
        /** @description OK */
        EnvelopeAuction: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Envelope"] & {
                    data?: components["schemas"]["AuctionSnapshot"];
                };
            };
        };
        /** @description OK */
        EnvelopeAuctionPage: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Envelope"] & {
                    data?: components["schemas"]["AuctionPage"];
                };
            };
        };
        /** @description OK */
        EnvelopeBidPage: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Envelope"] & {
                    data?: components["schemas"]["BidPage"];
                };
            };
        };
        /** @description OK */
        EnvelopeBidResult: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Envelope"] & {
                    data?: components["schemas"]["BidResult"];
                };
            };
        };
        /** @description OK */
        EnvelopeResult: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Envelope"] & {
                    data?: components["schemas"]["AuctionResult"];
                };
            };
        };
        /** @description OK */
        EnvelopeParticipant: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Envelope"] & {
                    data?: components["schemas"]["Participant"];
                };
            };
        };
        /** @description Created; token is returned once */
        EnvelopeAgentToken: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Envelope"] & {
                    data?: components["schemas"]["AgentToken"];
                };
            };
        };
        /** @description OK */
        EnvelopeAgentTokenPage: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Envelope"] & {
                    data?: components["schemas"]["AgentTokenPage"];
                };
            };
        };
        /** @description Invalid request */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Envelope"];
            };
        };
        /** @description Authentication required */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Envelope"];
            };
        };
        /** @description Permission denied */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Envelope"];
            };
        };
        /** @description Resource not found */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Envelope"];
            };
        };
        /** @description Business conflict such as BID_TOO_LOW */
        Conflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Envelope"];
            };
        };
        /** @description Rate limited */
        RateLimited: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Envelope"];
            };
        };
    };
    parameters: {
        AuctionId: string;
        /**
         * @description 幂等键的可选写法。优先使用 BidRequest.requestId；只有本头而无 requestId 时以本头为准，
         *     两者同时出现且不一致时返回 400 VALIDATION_FAILED（因为无法判断调用方真实意图，
         *     猜错会把一次重试当成新出价，造成重复冻结）。
         */
        IdempotencyKey: string;
        Page: number;
        Size: number;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            200: components["responses"]["EnvelopeAuth"];
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
        };
    };
    createWebSocketTicket: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["EnvelopeWsTicket"];
            401: components["responses"]["Unauthorized"];
            429: components["responses"]["RateLimited"];
        };
    };
    currentUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["EnvelopeUser"];
            401: components["responses"]["Unauthorized"];
        };
    };
    currentWallet: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["EnvelopeWallet"];
            401: components["responses"]["Unauthorized"];
        };
    };
    walletLedger: {
        parameters: {
            query?: {
                page?: components["parameters"]["Page"];
                size?: components["parameters"]["Size"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["EnvelopeLedgerPage"];
            401: components["responses"]["Unauthorized"];
        };
    };
    listAuctions: {
        parameters: {
            query?: {
                status?: components["schemas"]["AuctionStatus"];
                page?: components["parameters"]["Page"];
                size?: components["parameters"]["Size"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["EnvelopeAuctionPage"];
            401: components["responses"]["Unauthorized"];
        };
    };
    getAuction: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                auctionId: components["parameters"]["AuctionId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["EnvelopeAuction"];
            404: components["responses"]["NotFound"];
        };
    };
    joinAuction: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                auctionId: components["parameters"]["AuctionId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["EnvelopeParticipant"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };
    listBids: {
        parameters: {
            query?: {
                page?: components["parameters"]["Page"];
                size?: components["parameters"]["Size"];
            };
            header?: never;
            path: {
                auctionId: components["parameters"]["AuctionId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["EnvelopeBidPage"];
            404: components["responses"]["NotFound"];
        };
    };
    placeBid: {
        parameters: {
            query?: never;
            header?: {
                /**
                 * @description 幂等键的可选写法。优先使用 BidRequest.requestId；只有本头而无 requestId 时以本头为准，
                 *     两者同时出现且不一致时返回 400 VALIDATION_FAILED（因为无法判断调用方真实意图，
                 *     猜错会把一次重试当成新出价，造成重复冻结）。
                 */
                "Idempotency-Key"?: components["parameters"]["IdempotencyKey"];
            };
            path: {
                auctionId: components["parameters"]["AuctionId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BidRequest"];
            };
        };
        responses: {
            200: components["responses"]["EnvelopeBidResult"];
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            429: components["responses"]["RateLimited"];
        };
    };
    auctionResult: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                auctionId: components["parameters"]["AuctionId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["EnvelopeResult"];
            404: components["responses"]["NotFound"];
        };
    };
    createAuction: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateAuctionRequest"];
            };
        };
        responses: {
            201: components["responses"]["EnvelopeAuction"];
            403: components["responses"]["Forbidden"];
        };
    };
    startAuction: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                auctionId: components["parameters"]["AuctionId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["EnvelopeAuction"];
            403: components["responses"]["Forbidden"];
            409: components["responses"]["Conflict"];
        };
    };
    cancelAuction: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                auctionId: components["parameters"]["AuctionId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["EnvelopeAuction"];
            403: components["responses"]["Forbidden"];
            409: components["responses"]["Conflict"];
        };
    };
    auctionLedger: {
        parameters: {
            query?: {
                page?: components["parameters"]["Page"];
                size?: components["parameters"]["Size"];
            };
            header?: never;
            path: {
                auctionId: components["parameters"]["AuctionId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["EnvelopeLedgerPage"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    listAgentTokens: {
        parameters: {
            query?: {
                page?: components["parameters"]["Page"];
                size?: components["parameters"]["Size"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["EnvelopeAgentTokenPage"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    createAgentToken: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateAgentTokenRequest"];
            };
        };
        responses: {
            201: components["responses"]["EnvelopeAgentToken"];
            403: components["responses"]["Forbidden"];
        };
    };
    revokeAgentToken: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tokenId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["EnvelopeAgentToken"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    listMyAgentTokens: {
        parameters: {
            query?: {
                page?: components["parameters"]["Page"];
                size?: components["parameters"]["Size"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["EnvelopeAgentTokenPage"];
            401: components["responses"]["Unauthorized"];
        };
    };
    createMyAgentToken: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateMyAgentTokenRequest"];
            };
        };
        responses: {
            201: components["responses"]["EnvelopeAgentToken"];
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
        };
    };
    revokeMyAgentToken: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tokenId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["EnvelopeAgentToken"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    agentAuction: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                auctionId: components["parameters"]["AuctionId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["EnvelopeAuction"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            429: components["responses"]["RateLimited"];
        };
    };
    agentBid: {
        parameters: {
            query?: never;
            header?: {
                /**
                 * @description 幂等键的可选写法。优先使用 BidRequest.requestId；只有本头而无 requestId 时以本头为准，
                 *     两者同时出现且不一致时返回 400 VALIDATION_FAILED（因为无法判断调用方真实意图，
                 *     猜错会把一次重试当成新出价，造成重复冻结）。
                 */
                "Idempotency-Key"?: components["parameters"]["IdempotencyKey"];
            };
            path: {
                auctionId: components["parameters"]["AuctionId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BidRequest"];
            };
        };
        responses: {
            200: components["responses"]["EnvelopeBidResult"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            409: components["responses"]["Conflict"];
            429: components["responses"]["RateLimited"];
        };
    };
    agentAuctionResult: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                auctionId: components["parameters"]["AuctionId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["EnvelopeResult"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
}
