/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/ws-tickets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * @description 领一张一次性 WebSocket 入场券（默认 60 秒有效）。
         *
         *     为什么不让客户端把 JWT 直接放进 WS 的 URL：浏览器无法在 WebSocket 握手上自定义头，
         *     令牌只能进查询串，而查询串会落进访问日志与浏览器历史——把一个长效凭证留在日志里。
         *     换成一次性短票后，日志里最坏只会留下一个已作废的字符串。
         *
         *     用法：拿到 ticket 后连 `ws(s)://<host>:<wsPort>/ws/auctions/{auctionId}?ticket=<ticket>`。
         *     票只能核销一次，重复使用会被拒绝（先收到 CONNECTION_STATE(connected=false)，再被断开）。
         */
        post: operations["createWebSocketTicket"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["currentUser"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/wallets/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["currentWallet"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/wallets/me/ledger": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["walletLedger"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auctions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listAuctions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auctions/{auctionId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getAuction"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auctions/{auctionId}/join": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["joinAuction"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auctions/{auctionId}/bids": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listBids"];
        put?: never;
        /**
         * @description 提交出价。幂等键以请求体的 requestId 为准；也可以用 Idempotency-Key 头代替。
         *     重复提交同一个幂等键时返回**首次**结果，code 为 IDEMPOTENCY_REPLAY（HTTP 仍是 200），
         *     客户端据此可以安全重试。
         */
        post: operations["placeBid"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auctions/{auctionId}/result": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["auctionResult"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/auctions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["createAuction"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/auctions/{auctionId}/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["startAuction"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/auctions/{auctionId}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["cancelAuction"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/agent-tokens": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["createAgentToken"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/agent-tokens/{tokenId}/revoke": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["revokeAgentToken"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/agent/auctions/{auctionId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["agentAuction"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/agent/auctions/{auctionId}/bids": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["agentBid"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/agent/auctions/{auctionId}/result": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["agentAuctionResult"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Envelope: {
            code: components["schemas"]["ApiCode"];
            /** @example ok */
            message: string;
            data: unknown;
            requestId: string;
        };
        /**
         * @description 业务结果码，所有响应的 code 字段取值。HTTP 状态码与之一一对应：
         *     OK=200；VALIDATION_FAILED=400；UNAUTHENTICATED=401；FORBIDDEN=403；
         *     NOT_FOUND=404；METHOD_NOT_ALLOWED=405；其余冲突类=409；RATE_LIMITED=429；INTERNAL_ERROR=500。
         *     客户端应以 code 判定业务结果，不要只依赖 HTTP 状态码。
         *     两个成功码 OK 与 IDEMPOTENCY_REPLAY 都对应 200。
         * @enum {string}
         */
        ApiCode: "OK" | "VALIDATION_FAILED" | "UNAUTHENTICATED" | "FORBIDDEN" | "NOT_FOUND" | "INVALID_STATE" | "BID_TOO_LOW" | "BID_LATE" | "NOT_JOINED" | "INSUFFICIENT_BALANCE" | "IDEMPOTENCY_REPLAY" | "CONFLICT" | "METHOD_NOT_ALLOWED" | "RATE_LIMITED" | "INTERNAL_ERROR";
        LoginRequest: {
            /** Format: email */
            email: string;
            /** Format: password */
            password: string;
        };
        AuthData: {
            accessToken?: string;
            /** Format: date-time */
            expiresAt?: string;
            user?: components["schemas"]["User"];
        };
        User: {
            id: string;
            name: string;
            /** @enum {string} */
            role: "BIDDER" | "ADMIN";
        };
        /** @enum {string} */
        AuctionStatus: "DRAFT" | "RUNNING" | "SETTLING" | "FINISHED" | "CANCELLED";
        AuctionSnapshot: {
            id: string;
            title: string;
            description?: string;
            status: components["schemas"]["AuctionStatus"];
            startPrice: number;
            minIncrement: number;
            currentPrice: number;
            leader?: string | null;
            /** Format: date-time */
            endsAt?: string | null;
            extensionCount: number;
            participantCount: number;
            seq: number;
            /** Format: date-time */
            serverTime: string;
        };
        BidRequest: {
            requestId: string;
            amount: number;
        };
        BidResult: {
            accepted?: boolean;
            idempotent?: boolean;
            price?: number;
            leader?: string | null;
            extensions?: number;
            seq?: number;
            /** Format: date-time */
            serverTime?: string;
        };
        /** @description 一条已接受的出价记录。seq 单调递增，客户端据此检测事件缺口。 */
        Bid: {
            id: string;
            userId: string;
            amount: number;
            requestId: string;
            seq: number;
            /** Format: date-time */
            serverTime: string;
        };
        AuctionPage: {
            items: components["schemas"]["AuctionSnapshot"][];
            page: number;
            size: number;
            total: number;
        };
        BidPage: {
            items: components["schemas"]["Bid"][];
            page: number;
            size: number;
            total: number;
        };
        LedgerPage: {
            items: components["schemas"]["LedgerEntry"][];
            page: number;
            size: number;
            total: number;
        };
        CreateAuctionRequest: {
            title: string;
            description?: string;
            startPrice: number;
            minIncrement: number;
            durationSeconds: number;
        };
        CreateAgentTokenRequest: {
            name: string;
            agentUserId: string;
            auctionIds?: string[];
            scopes: ("auction:read" | "auction:bid")[];
            /** Format: date-time */
            expiresAt: string;
        };
        Wallet: {
            totalBalance?: number;
            frozenAmount?: number;
            availableBalance?: number;
        };
        LedgerEntry: {
            id: string;
            /** @enum {string} */
            type: "FREEZE" | "RELEASE" | "SETTLE";
            amount: number;
            auctionId?: string | null;
            /**
             * @description 触发本条流水的那次请求的幂等键，用于把资金变动追回到具体出价/结算。
             *     结算产生的流水没有客户端请求，此处可能为空。
             */
            requestId?: string | null;
            /** Format: date-time */
            createdAt: string;
        };
        ErrorData: {
            [key: string]: unknown;
        };
        WsTicket: {
            /** @description 一次性入场券。base64url、无填充，可直接放进查询串。 */
            ticket: string;
            /** Format: date-time */
            expiresAt: string;
            /**
             * @description 连接路径模板，把 `{auctionId}` 换成目标拍品 ID。服务端给出而不是让前端硬编码：
             *     路径属于契约，改一次就该只改一处。
             */
            wsPath: string;
            /**
             * @description WebSocket 监听的端口。它与 HTTP 端口**不同**（默认是 `WS_PORT`，没配时是 HTTP 端口 + 10000），
             *     因此必须由服务端告知，客户端不能拿它当 80/443 去拼。
             */
            wsPort: number;
        };
        Participant: {
            auctionId?: string;
            userId?: string;
            /** Format: date-time */
            joinedAt?: string;
        };
        AuctionResult: {
            auctionId: string;
            status: components["schemas"]["AuctionStatus"];
            winner?: string | null;
            finalPrice: number;
            /** @enum {string} */
            reason: "TIMEOUT" | "NO_BIDS" | "CANCELLED";
            /** Format: date-time */
            settledAt?: string | null;
        };
        AgentToken: {
            token?: string;
            tokenId?: string;
            /** Format: date-time */
            expiresAt?: string;
        };
    };
    responses: {
        /** @description OK */
        EnvelopeAuth: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Envelope"] & {
                    data?: components["schemas"]["AuthData"];
                };
            };
        };
        /** @description OK */
        EnvelopeWsTicket: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Envelope"] & {
                    data?: components["schemas"]["WsTicket"];
                };
            };
        };
        /** @description OK */
        EnvelopeUser: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Envelope"] & {
                    data?: components["schemas"]["User"];
                };
            };
        };
        /** @description OK */
        EnvelopeWallet: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Envelope"] & {
                    data?: components["schemas"]["Wallet"];
                };
            };
        };
        /** @description OK */
        EnvelopeLedgerPage: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Envelope"] & {
                    data?: components["schemas"]["LedgerPage"];
                };
            };
        };
        /** @description OK */
        EnvelopeAuction: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Envelope"] & {
                    data?: components["schemas"]["AuctionSnapshot"];
                };
            };
        };
        /** @description OK */
        EnvelopeAuctionPage: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Envelope"] & {
                    data?: components["schemas"]["AuctionPage"];
                };
            };
        };
        /** @description OK */
        EnvelopeBidPage: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Envelope"] & {
                    data?: components["schemas"]["BidPage"];
                };
            };
        };
        /** @description OK */
        EnvelopeBidResult: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Envelope"] & {
                    data?: components["schemas"]["BidResult"];
                };
            };
        };
        /** @description OK */
        EnvelopeResult: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Envelope"] & {
                    data?: components["schemas"]["AuctionResult"];
                };
            };
        };
        /** @description OK */
        EnvelopeParticipant: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Envelope"] & {
                    data?: components["schemas"]["Participant"];
                };
            };
        };
        /** @description Created; token is returned once */
        EnvelopeAgentToken: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Envelope"] & {
                    data?: components["schemas"]["AgentToken"];
                };
            };
        };
        /** @description Invalid request */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Envelope"];
            };
        };
        /** @description Authentication required */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Envelope"];
            };
        };
        /** @description Permission denied */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Envelope"];
            };
        };
        /** @description Resource not found */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Envelope"];
            };
        };
        /** @description Business conflict such as BID_TOO_LOW */
        Conflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Envelope"];
            };
        };
        /** @description Rate limited */
        RateLimited: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Envelope"];
            };
        };
    };
    parameters: {
        AuctionId: string;
        /**
         * @description 幂等键的可选写法。优先使用 BidRequest.requestId；只有本头而无 requestId 时以本头为准，
         *     两者同时出现且不一致时返回 400 VALIDATION_FAILED（因为无法判断调用方真实意图，
         *     猜错会把一次重试当成新出价，造成重复冻结）。
         */
        IdempotencyKey: string;
        Page: number;
        Size: number;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            200: components["responses"]["EnvelopeAuth"];
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
        };
    };
    createWebSocketTicket: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["EnvelopeWsTicket"];
            401: components["responses"]["Unauthorized"];
            429: components["responses"]["RateLimited"];
        };
    };
    currentUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["EnvelopeUser"];
            401: components["responses"]["Unauthorized"];
        };
    };
    currentWallet: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["EnvelopeWallet"];
            401: components["responses"]["Unauthorized"];
        };
    };
    walletLedger: {
        parameters: {
            query?: {
                page?: components["parameters"]["Page"];
                size?: components["parameters"]["Size"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["EnvelopeLedgerPage"];
            401: components["responses"]["Unauthorized"];
        };
    };
    listAuctions: {
        parameters: {
            query?: {
                status?: components["schemas"]["AuctionStatus"];
                page?: components["parameters"]["Page"];
                size?: components["parameters"]["Size"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["EnvelopeAuctionPage"];
            401: components["responses"]["Unauthorized"];
        };
    };
    getAuction: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                auctionId: components["parameters"]["AuctionId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["EnvelopeAuction"];
            404: components["responses"]["NotFound"];
        };
    };
    joinAuction: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                auctionId: components["parameters"]["AuctionId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["EnvelopeParticipant"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };
    listBids: {
        parameters: {
            query?: {
                page?: components["parameters"]["Page"];
                size?: components["parameters"]["Size"];
            };
            header?: never;
            path: {
                auctionId: components["parameters"]["AuctionId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["EnvelopeBidPage"];
            404: components["responses"]["NotFound"];
        };
    };
    placeBid: {
        parameters: {
            query?: never;
            header?: {
                /**
                 * @description 幂等键的可选写法。优先使用 BidRequest.requestId；只有本头而无 requestId 时以本头为准，
                 *     两者同时出现且不一致时返回 400 VALIDATION_FAILED（因为无法判断调用方真实意图，
                 *     猜错会把一次重试当成新出价，造成重复冻结）。
                 */
                "Idempotency-Key"?: components["parameters"]["IdempotencyKey"];
            };
            path: {
                auctionId: components["parameters"]["AuctionId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BidRequest"];
            };
        };
        responses: {
            200: components["responses"]["EnvelopeBidResult"];
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            429: components["responses"]["RateLimited"];
        };
    };
    auctionResult: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                auctionId: components["parameters"]["AuctionId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["EnvelopeResult"];
            404: components["responses"]["NotFound"];
        };
    };
    createAuction: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateAuctionRequest"];
            };
        };
        responses: {
            201: components["responses"]["EnvelopeAuction"];
            403: components["responses"]["Forbidden"];
        };
    };
    startAuction: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                auctionId: components["parameters"]["AuctionId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["EnvelopeAuction"];
            403: components["responses"]["Forbidden"];
            409: components["responses"]["Conflict"];
        };
    };
    cancelAuction: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                auctionId: components["parameters"]["AuctionId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["EnvelopeAuction"];
            403: components["responses"]["Forbidden"];
            409: components["responses"]["Conflict"];
        };
    };
    createAgentToken: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateAgentTokenRequest"];
            };
        };
        responses: {
            201: components["responses"]["EnvelopeAgentToken"];
            403: components["responses"]["Forbidden"];
        };
    };
    revokeAgentToken: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tokenId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["EnvelopeAgentToken"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    agentAuction: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                auctionId: components["parameters"]["AuctionId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["EnvelopeAuction"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    agentBid: {
        parameters: {
            query?: never;
            header?: {
                /**
                 * @description 幂等键的可选写法。优先使用 BidRequest.requestId；只有本头而无 requestId 时以本头为准，
                 *     两者同时出现且不一致时返回 400 VALIDATION_FAILED（因为无法判断调用方真实意图，
                 *     猜错会把一次重试当成新出价，造成重复冻结）。
                 */
                "Idempotency-Key"?: components["parameters"]["IdempotencyKey"];
            };
            path: {
                auctionId: components["parameters"]["AuctionId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BidRequest"];
            };
        };
        responses: {
            200: components["responses"]["EnvelopeBidResult"];
            409: components["responses"]["Conflict"];
            429: components["responses"]["RateLimited"];
        };
    };
    agentAuctionResult: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                auctionId: components["parameters"]["AuctionId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["EnvelopeResult"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
}
